import { createHomeMainSection } from './js/home-best-sellers';
import './js/header';
import './js/categories-list.js';
import './js/support-ua';
import './js/home-best-sellers';
import './js/books-by-category';
import './js/book-modal/book-modal';
import './js/window-reload';
import './js/mobile-menu';
import './js/auth/auth.js';
import './js/modal-footer-team';
import './js/burger';
import './js/scroll-up';
